# Generated by Django 6.0.1 on 2026-02-12 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('deactivate', 'Deactivated'), ('activate', 'Activated'), ('approve', 'Approved'), ('reject', 'Rejected'), ('flag', 'Flagged'), ('unflag', 'Unflagged'), ('export', 'Exported'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Changed'), ('other', 'Other')], help_text='Type of action performed', max_length=20)),
                ('object_type', models.CharField(choices=[('user', 'User'), ('app', 'App'), ('category', 'Category'), ('review', 'Review'), ('link', 'Link'), ('settings', 'Settings'), ('content', 'Content')], help_text='Type of object affected', max_length=20)),
                ('object_id', models.IntegerField(help_text='ID of the object affected')),
                ('object_name', models.CharField(blank=True, help_text='Name/identifier of the affected object', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Details of what was changed (optional)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the admin', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information')),
                ('admin_user', models.ForeignKey(help_text='The admin/staff who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'), models.Index(fields=['admin_user', '-timestamp'], name='core_auditl_admin_u_0a9811_idx'), models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx')],
            },
        ),
    ]
