# Generated by Django 6.0.1 on 2026-02-13 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_email_verified_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Account Deletion OTP',
                'verbose_name_plural': 'Account Deletion OTPs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='When deletion was requested', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When account will be deleted (3 days after request)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pending_deletion',
            field=models.BooleanField(default=False, help_text='Account is pending deletion'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_pending_deletion'], name='accounts_us_is_pend_afcd11_idx'),
        ),
        migrations.AddField(
            model_name='accountdeletionotp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
