# Generated by Django 6.0.2 on 2026-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3498db', help_text='Hex color for category (e.g., #3498db)', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this category'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text="CSS class for icon (e.g., 'fas fa-gamepad')", max_length=60),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in listings'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('📱', 'Mobile'), ('🎮', 'Games'), ('📚', 'Books & Reference'), ('🎵', 'Music & Audio'), ('📹', 'Video Players'), ('📷', 'Photography'), ('🛒', 'Shopping'), ('🍔', 'Food & Drink'), ('🏋️', 'Health & Fitness'), ('🏠', 'Lifestyle'), ('📰', 'News & Magazines'), ('🎨', 'Art & Design'), ('🎓', 'Education'), ('💼', 'Business'), ('🛠️', 'Tools'), ('⚙️', 'Utilities'), ('🌐', 'Communication'), ('🔒', 'Security'), ('🎬', 'Entertainment'), ('📊', 'Productivity'), ('🚗', 'Travel & Local'), ('⚽', 'Sports'), ('🏥', 'Medical'), ('👶', 'Family')], default='📱', help_text='Emoji or icon representing this category', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category is visible to users'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (e.g., Games, Business, Education)', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the category name', max_length=140, unique=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categories__slug_9b1a28_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='categories__is_acti_3ca3e4_idx'),
        ),
    ]
