# Generated by Django 6.0.1 on 2026-02-11 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('total_scanned', models.IntegerField(default=0, help_text='Total files/patterns scanned')),
                ('django_urls_found', models.IntegerField(default=0, help_text='Django URL patterns found')),
                ('external_urls_found', models.IntegerField(default=0, help_text='External URLs found in code')),
                ('new_links_added', models.IntegerField(default=0, help_text='New links added to database')),
                ('duplicates_skipped', models.IntegerField(default=0, help_text='Duplicate links skipped')),
                ('scan_details', models.JSONField(default=dict, help_text='Detailed scan results')),
                ('scan_output', models.TextField(blank=True, help_text='Raw scan command output')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_scan_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Link Scan Reports',
                'ordering': ['-scan_date'],
            },
        ),
    ]
