# Generated by Django 6.0.1 on 2026-02-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_linkscanreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkScanReport',
        ),
    ]
