# Generated by Django 6.0.1 on 2026-01-29 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('windows', 'Windows'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='app_covers/')),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='apks/')),
                ('download_link', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='categories.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
