# Generated by Django 6.0.1 on 2026-02-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='apks/')),
                ('download_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='apps.app')),
            ],
            options={
                'ordering': ['-released_at'],
                'unique_together': {('app', 'version_number')},
            },
        ),
    ]
