# Generated by Django 6.0.1 on 2026-02-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='store_name',
            field=models.CharField(blank=True, default='JN App Store', max_length=100),
        ),
    ]
