# Generated by Django 6.0.1 on 2026-02-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_app_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
