# Generated by Django 6.0.1 on 2026-02-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_app_store_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_pending_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
