# Generated by Django 6.0.1 on 2026-02-11 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_app_is_pending_deletion'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='age_rating',
            field=models.CharField(choices=[('3+', '3+ years'), ('7+', '7+ years'), ('12+', '12+ years'), ('16+', '16+ years'), ('18+', '18+ years')], default='3+', max_length=10),
        ),
        migrations.AddField(
            model_name='app',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average user rating (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='app',
            name='developer_email',
            field=models.EmailField(blank=True, help_text='Developer email', max_length=254),
        ),
        migrations.AddField(
            model_name='app',
            name='developer_name',
            field=models.CharField(blank=True, help_text='Developer/Publisher name', max_length=120),
        ),
        migrations.AddField(
            model_name='app',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of APK for verification', max_length=64),
        ),
        migrations.AddField(
            model_name='app',
            name='has_iap',
            field=models.BooleanField(default=False, help_text='Has in-app purchases'),
        ),
        migrations.AddField(
            model_name='app',
            name='install_count',
            field=models.PositiveIntegerField(default=0, help_text='Estimated install count'),
        ),
        migrations.AddField(
            model_name='app',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='app',
            name='last_update_date',
            field=models.DateField(auto_now=True, help_text='Date of last update'),
        ),
        migrations.AddField(
            model_name='app',
            name='min_api_level',
            field=models.IntegerField(default=21, help_text='Minimum Android API level'),
        ),
        migrations.AddField(
            model_name='app',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD (if not free)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='privacy_policy_url',
            field=models.URLField(blank=True, help_text='Privacy policy URL'),
        ),
        migrations.AddField(
            model_name='app',
            name='release_date',
            field=models.DateField(default='2026-01-29', help_text='Date when app was first published'),
        ),
        migrations.AddField(
            model_name='app',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original source/home page of the app'),
        ),
        migrations.AddField(
            model_name='app',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Support/Contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='app',
            name='target_api_level',
            field=models.IntegerField(default=35, help_text='Target Android API level'),
        ),
        migrations.AddField(
            model_name='app',
            name='terms_url',
            field=models.URLField(blank=True, help_text='Terms of service URL'),
        ),
        migrations.AddField(
            model_name='app',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings'),
        ),
        migrations.AddField(
            model_name='app',
            name='website_url',
            field=models.URLField(blank=True, help_text='Developer website'),
        ),
        migrations.AlterField(
            model_name='app',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Direct APK file', null=True, upload_to='apks/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='download_link',
            field=models.URLField(blank=True, help_text='External download link (Google Drive, etc)'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['slug'], name='apps_app_slug_2aa5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['platform'], name='apps_app_platfor_ac373a_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['created_at'], name='apps_app_created_fdae32_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['avg_rating'], name='apps_app_avg_rat_3c3ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['-downloads'], name='apps_app_downloa_0546bb_idx'),
        ),
    ]
