# Generated by Django 6.0.2 on 2026-02-11 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_app_age_rating_app_avg_rating_app_developer_email_and_more'),
        ('categories', '0002_alter_category_options_category_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['-created_at'], 'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterField(
            model_name='app',
            name='age_rating',
            field=models.CharField(choices=[('3+', '3+ years'), ('7+', '7+ years'), ('12+', '12+ years'), ('16+', '16+ years'), ('18+', '18+ years')], default='3+', help_text='Appropriate age rating', max_length=10),
        ),
        migrations.AlterField(
            model_name='app',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Direct APK file for download', null=True, upload_to='apks/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average user rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.ForeignKey(help_text='Category this app belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='app',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='App cover/thumbnail image', null=True, upload_to='app_covers/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this listing was created'),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the app'),
        ),
        migrations.AlterField(
            model_name='app',
            name='downloads',
            field=models.PositiveIntegerField(default=0, help_text='Total download count'),
        ),
        migrations.AlterField(
            model_name='app',
            name='has_iap',
            field=models.BooleanField(default=False, help_text='Has in-app purchases?'),
        ),
        migrations.AlterField(
            model_name='app',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Is this app free?'),
        ),
        migrations.AlterField(
            model_name='app',
            name='is_pending_deletion',
            field=models.BooleanField(default=False, help_text='Marked for deletion?'),
        ),
        migrations.AlterField(
            model_name='app',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Is this app published/visible?'),
        ),
        migrations.AlterField(
            model_name='app',
            name='min_api_level',
            field=models.IntegerField(default=21, help_text='Minimum Android API level (21 = Android 5.0)'),
        ),
        migrations.AlterField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(help_text='User who uploaded this app', on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('windows', 'Windows'), ('ios', 'iOS'), ('web', 'Web'), ('other', 'Other')], default='android', help_text='Platform this app runs on', max_length=20),
        ),
        migrations.AlterField(
            model_name='app',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD (if not free)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='app',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description (1 line)', max_length=220),
        ),
        migrations.AlterField(
            model_name='app',
            name='size_mb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='App size in megabytes', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='store_email',
            field=models.EmailField(blank=True, help_text='Store contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='app',
            name='store_name',
            field=models.CharField(blank=True, default='JN App Store', help_text='Store name (for credits)', max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='target_api_level',
            field=models.IntegerField(default=35, help_text='Target Android API level (35 = Android 15)'),
        ),
        migrations.AlterField(
            model_name='app',
            name='title',
            field=models.CharField(help_text='App name/title', max_length=180),
        ),
        migrations.AlterField(
            model_name='app',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last modified'),
        ),
        migrations.AlterField(
            model_name='app',
            name='version',
            field=models.CharField(blank=True, help_text='Current version number (e.g., 1.0.0)', max_length=40),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['category'], name='apps_app_categor_1bd084_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['is_published'], name='apps_app_is_publ_f0fbdd_idx'),
        ),
    ]
