# Generated by Django 6.0.2 on 2026-02-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_app_options_alter_app_age_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.CharField(choices=[('android', 'Android')], default='android', editable=False, help_text='Platform this app runs on (Android only)', max_length=20),
        ),
    ]
