# Generated by Django 6.0.2 on 2026-02-11 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_app_platform'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='app',
            name='apps_app_platfor_ac373a_idx',
        ),
        migrations.AddField(
            model_name='app',
            name='min_android_version',
            field=models.CharField(default='5.0', help_text='Minimum Android version (e.g., 5.0, 6.0, 7.0)', max_length=10),
        ),
        migrations.AddField(
            model_name='app',
            name='target_android_version',
            field=models.CharField(default='15.0', help_text='Target Android version (e.g., 13.0, 14.0, 15.0)', max_length=10),
        ),
        migrations.AlterField(
            model_name='app',
            name='min_api_level',
            field=models.IntegerField(default=21, help_text='Minimum Android API level required (21 = Android 5.0 Lollipop)'),
        ),
        migrations.AlterField(
            model_name='app',
            name='size_mb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='APK size in megabytes', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='app',
            name='target_api_level',
            field=models.IntegerField(default=35, help_text='Target Android API level (35 = Android 15 VanillaIceCream)'),
        ),
        migrations.AlterField(
            model_name='app',
            name='version',
            field=models.CharField(blank=True, help_text='Current app version (e.g., 1.0.0)', max_length=40),
        ),
        migrations.RemoveField(
            model_name='app',
            name='platform',
        ),
    ]
