# Generated by Django 6.0.1 on 2026-02-12 21:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_app_apps_app_platfor_ac373a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'ordering': ['-released_at'], 'verbose_name_plural': 'App Versions'},
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='apk_file',
        ),
        migrations.AddField(
            model_name='appversion',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash', max_length=64),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='app',
            field=models.ForeignKey(help_text='App this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='apps.app'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='description',
            field=models.TextField(blank=True, help_text="What's new in this version"),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='download_link',
            field=models.URLField(blank=True, help_text='Download link for this version'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this version available for download?'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='released_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Release date and time'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='size_mb',
            field=models.DecimalField(decimal_places=2, help_text='App size in megabytes', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version_number',
            field=models.CharField(help_text='Version number (e.g., 1.0.1)', max_length=40),
        ),
    ]
