# Generated by Django 6.0.1 on 2026-02-19 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_appscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='copyright_claim_reason',
            field=models.TextField(blank=True, help_text='Reason for copyright claim if applicable'),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_statement',
            field=models.TextField(blank=True, default='This app is the original creation of the developer listed above.', help_text='Copyright claim statement'),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_verified',
            field=models.BooleanField(default=False, help_text='Admin verified copyright claims'),
        ),
        migrations.AddField(
            model_name='app',
            name='has_copyright_claim',
            field=models.BooleanField(default=False, help_text='Does this app have a copyright/DMCA claim against it?'),
        ),
        migrations.AddField(
            model_name='app',
            name='is_original_content',
            field=models.BooleanField(default=True, help_text='I confirm this is original content and I have rights to distribute it'),
        ),
        migrations.AddField(
            model_name='app',
            name='takedown_reason',
            field=models.TextField(blank=True, help_text='Reason for owner-requested takedown'),
        ),
        migrations.AddField(
            model_name='app',
            name='takedown_requested',
            field=models.BooleanField(default=False, help_text='Owner requested takedown?'),
        ),
        migrations.AddField(
            model_name='app',
            name='takedown_requested_at',
            field=models.DateTimeField(blank=True, help_text='When takedown was requested', null=True),
        ),
        migrations.CreateModel(
            name='CopyrightClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('dmca', 'DMCA Takedown Notice'), ('owner_request', 'Owner Requested Takedown'), ('counter_notice', 'Counter-Notice')], default='dmca', help_text='Type of claim', max_length=20)),
                ('claimant_name', models.CharField(help_text='Name of person/organization filing claim', max_length=200)),
                ('claimant_email', models.EmailField(help_text='Claimant email', max_length=254)),
                ('claimant_address', models.TextField(blank=True, help_text='Claimant address')),
                ('description', models.TextField(help_text='Description of copyrighted work being infringed')),
                ('reason', models.TextField(help_text='Reason for claim (detailed explanation)')),
                ('evidence_url', models.URLField(blank=True, help_text='URL to original/competing work')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Takedown Approved'), ('rejected', 'Rejected - No Action Taken'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('appealed', 'Counter-Notice Filed (Appealed)')], default='pending', help_text='Claim status', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin review')),
                ('action_taken', models.TextField(blank=True, help_text='What action was taken (if any)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(help_text='App being claimed', on_delete=django.db.models.deletion.CASCADE, related_name='copyright_claims', to='apps.app')),
            ],
            options={
                'verbose_name': 'Copyright Claim',
                'verbose_name_plural': 'Copyright Claims',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['app', '-submitted_at'], name='apps_copyri_app_id_7e9e53_idx'), models.Index(fields=['status'], name='apps_copyri_status_9ed9f3_idx')],
            },
        ),
    ]
