# Generated by Django 6.0.1 on 2026-02-19 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_app_copyright_claim_reason_app_copyright_statement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='copyright_dispute_status',
            field=models.CharField(choices=[('none', 'No Dispute'), ('under_investigation', 'Under Investigation'), ('disputed', 'Disputed/Contested'), ('resolved', 'Resolved')], default='none', help_text='Current dispute status', max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_expiration_date',
            field=models.DateField(blank=True, help_text='When copyright protection expires (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_holder_email',
            field=models.EmailField(blank=True, help_text='Email of copyright holder for verification', max_length=254),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_holder_verified',
            field=models.BooleanField(default=False, help_text='Copyright holder email verified?'),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_infringement_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of infringement reports'),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_license_type',
            field=models.CharField(choices=[('proprietary', 'Proprietary/Commercial'), ('mit', 'MIT License'), ('gpl', 'GPL License'), ('apache', 'Apache License'), ('bsd', 'BSD License'), ('custom', 'Custom License'), ('public_domain', 'Public Domain')], default='proprietary', help_text='Type of license/copyright protection', max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_license_url',
            field=models.URLField(blank=True, help_text='URL to license details or full license text'),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_notice_required',
            field=models.BooleanField(default=True, help_text='Must show copyright notice in app'),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_protection_level',
            field=models.CharField(choices=[('basic', 'Basic - Developer Statement Only'), ('standard', 'Standard - Admin Verified'), ('premium', 'Premium - Registered & Verified')], default='basic', help_text='Level of copyright protection', max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_registration_number',
            field=models.CharField(blank=True, help_text='Official copyright/trademark registration number', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified copyright', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='copyright_verified_date',
            field=models.DateTimeField(blank=True, help_text='When copyright was verified by admin', null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='has_infringement_report',
            field=models.BooleanField(default=False, help_text='Has any infringement reports against this app?'),
        ),
        migrations.CreateModel(
            name='CopyrightDisputeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the dispute')),
                ('resolution_status', models.CharField(choices=[('open', 'Open - Awaiting Resolution'), ('negotiation', 'Under Negotiation'), ('mediation', 'Mediation In Progress'), ('resolved_agree', 'Resolved - Both Parties Agree'), ('resolved_takedown', 'Resolved - App Removed'), ('resolved_other', 'Resolved - Other Outcome'), ('cancelled', 'Cancelled')], default='open', help_text='Current dispute resolution status', max_length=20)),
                ('resolution_terms', models.TextField(blank=True, help_text='Agreed upon resolution terms')),
                ('last_communication', models.DateTimeField(blank=True, help_text='Last communication with parties', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(help_text='App in dispute', on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='apps.app')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin assigned to handle dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_cases', to=settings.AUTH_USER_MODEL)),
                ('copyright_claim', models.OneToOneField(help_text='Associated copyright claim', on_delete=django.db.models.deletion.CASCADE, related_name='dispute_resolution', to='apps.copyrightclaim')),
            ],
            options={
                'verbose_name': 'Copyright Dispute Resolution',
                'verbose_name_plural': 'Copyright Dispute Resolutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyrightVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique verification token', max_length=100, unique=True)),
                ('email', models.EmailField(help_text='Email to verify', max_length=254)),
                ('is_verified', models.BooleanField(default=False, help_text='Has email been verified?')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Verification attempts made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('app', models.OneToOneField(help_text='App being verified', on_delete=django.db.models.deletion.CASCADE, related_name='copyright_verification', to='apps.app')),
            ],
            options={
                'verbose_name': 'Copyright Verification Token',
                'verbose_name_plural': 'Copyright Verification Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyrightInfringementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(help_text='Name of person reporting', max_length=200)),
                ('reporter_email', models.EmailField(help_text='Reporter email', max_length=254)),
                ('title', models.CharField(help_text='Brief title of the report', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of infringement')),
                ('original_app_name', models.CharField(blank=True, help_text='Name of original app (if applicable)', max_length=255)),
                ('original_app_url', models.URLField(blank=True, help_text='Link to original work')),
                ('evidence_description', models.TextField(blank=True, help_text='Specific details about what was copied')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified - Infringement Confirmed'), ('dismissed', 'Dismissed - No Infringement'), ('resolved', 'Resolved')], default='submitted', help_text='Report status', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text="Admin's investigation notes")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(help_text='App being reported', on_delete=django.db.models.deletion.CASCADE, related_name='infringement_reports', to='apps.app')),
            ],
            options={
                'verbose_name': 'Copyright Infringement Report',
                'verbose_name_plural': 'Copyright Infringement Reports',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['app', '-submitted_at'], name='apps_copyri_app_id_94b04e_idx'), models.Index(fields=['status'], name='apps_copyri_status_48633b_idx')],
            },
        ),
    ]
