# Generated by Django 6.0.1 on 2026-02-19 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_app_copyright_dispute_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='admin_review_notes',
            field=models.TextField(blank=True, help_text='Admin notes about copyright/ownership verification'),
        ),
        migrations.AddField(
            model_name='app',
            name='content_ownership_type',
            field=models.CharField(choices=[('original', 'I am the original creator'), ('permission', 'I have legal permission to share'), ('informational', 'Sharing for informational purposes')], default='informational', help_text='Declare your rights/ownership of this content', max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='developer_website',
            field=models.URLField(blank=True, help_text='Official developer website or portfolio', null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='legal_risk_level',
            field=models.CharField(choices=[('low', 'Low Risk - Verified Source'), ('medium', 'Medium Risk - Unverified Source'), ('high', 'High Risk - Requires Investigation')], default='medium', help_text='Legal/copyright risk assessment', max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='play_store_link',
            field=models.URLField(blank=True, help_text='Link to app on Google Play Store (if available)', null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='requires_manual_review',
            field=models.BooleanField(default=True, help_text='App requires manual copyright review before publication'),
        ),
        migrations.AddField(
            model_name='app',
            name='source_verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified the source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_verified_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='source_verified_date',
            field=models.DateTimeField(blank=True, help_text='When source was verified', null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='verified_external_link',
            field=models.BooleanField(default=False, help_text='Admin verified the external link (Play Store or official website)'),
        ),
    ]
