# Generated by Django 6.0.1 on 2026-02-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_app_admin_review_notes_app_content_ownership_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='store_name',
            field=models.CharField(blank=True, default='jndroid store', help_text='Store name (for credits)', max_length=100),
        ),
    ]
