# Generated by Django 4.2.10 on 2026-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_app_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='store_name',
            field=models.CharField(blank=True, default='JnDroid Store', help_text='Store name (for credits)', max_length=100),
        ),
    ]
